// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojrjlesnufsjuydcgmwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcmpsZXNudWZzanV5ZGNnbXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5OTkwNTEsImV4cCI6MjA1MTU3NTA1MX0.kyYMsGIQfw5GjNUEiXDFELd-EPOQ9NXvjGmyP_LMYJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);